services:
  node-app:
    image: nodeapp
    environment: 
      - PORT=5000
    ports:
      - 2000:5000
    volumes:
      - feedback:/app/feedback:ro
      - /Users/svoychik/Documents/Projects/util-node:/app:ro
      - /app/temp
      - /app/node_modules

volumes:
  feedback: